# Generated by Django 4.1.7 on 2023-03-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationid', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=100)),
                ('latitude', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StationAvailableSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot1', models.BooleanField(default=False)),
                ('slot2', models.BooleanField(default=False)),
                ('slot3', models.BooleanField(default=False)),
                ('slot4', models.BooleanField(default=False)),
                ('slot5', models.BooleanField(default=False)),
                ('slot6', models.BooleanField(default=False)),
                ('slot7', models.BooleanField(default=False)),
                ('slot8', models.BooleanField(default=False)),
                ('slot9', models.BooleanField(default=False)),
                ('slot10', models.BooleanField(default=False)),
                ('slot11', models.BooleanField(default=False)),
                ('slot12', models.BooleanField(default=False)),
                ('stationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.station')),
            ],
        ),
    ]
