# Generated by Django 4.1.7 on 2023-03-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stationavailableslots',
            unique_together={('stationid', 'date')},
        ),
        migrations.AlterModelTable(
            name='stationavailableslots',
            table='StationAvailableSlots',
        ),
    ]
