# Generated by Django 4.1.7 on 2023-03-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_stationavailableslots_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
