# Generated by Django 4.1.7 on 2023-03-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_station_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stationavailableslots',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stationavailableslots',
            name='slot1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stationavailableslots',
            name='slot10',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stationavailableslots',
            name='slot11',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stationavailableslots',
            name='slot12',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stationavailableslots',
            name='slot2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stationavailableslots',
            name='slot3',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stationavailableslots',
            name='slot4',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stationavailableslots',
            name='slot5',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stationavailableslots',
            name='slot6',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stationavailableslots',
            name='slot7',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stationavailableslots',
            name='slot8',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stationavailableslots',
            name='slot9',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='stationavailableslots',
            table=None,
        ),
    ]
